version: '3'

services:
  postgres:
    image: postgres:latest
    container_name: water-gas-service
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    ports:
      - 5432:5432


